"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Product = { id: string; name: string; slug: string; price: number; status: string; brand: string | null; is_featured: boolean };
type Category = { id: string; name: string };

export default function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [categoryId, setCategoryId] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { const supabase = createClient(); const [{ data: productData }, { data: categoryData }] = await Promise.all([supabase.from("products").select("id,name,slug,price,status,brand,is_featured").neq("status", "archived").order("sort_order").order("created_at", { ascending: false }), supabase.from("categories").select("id,name").eq("is_active", true).order("sort_order")]); setProducts(productData || []); setCategories(categoryData || []); }
  useEffect(() => { void load(); }, []);
  async function createProduct(event: React.FormEvent) { event.preventDefault(); setMessage(""); setError(""); const slug = name.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); const parsedPrice = Number(price.replace(/\./g, "").replace(",", ".")); if (!slug || !parsedPrice || parsedPrice < 0 || !categoryId) { setError("Completá nombre, precio y categoría."); return; } const supabase = createClient(); const { data: product, error: productError } = await supabase.from("products").insert({ name: name.trim(), slug, price: parsedPrice, status: "draft" }).select("id").single<{ id: string }>(); if (productError || !product) { setError(productError?.message.includes("duplicate") ? "Ya existe un producto con ese slug." : "No pudimos crear el producto."); return; } const { error: categoryError } = await supabase.from("product_categories").insert({ product_id: product.id, category_id: categoryId, is_primary: true }); if (categoryError) { setError("El producto se creó, pero no pudimos asignar la categoría."); return; } setName(""); setPrice(""); setCategoryId(""); setMessage("Producto creado como borrador."); await load(); }
  return <main className="admin"><header className="admin-head"><div className="admin-brand"><Link className="brand" href="/"><Image src="/LOGO.jpeg" alt="" width={35} height={35} /> chifle.</Link><div><span className="eyebrow">Catálogo</span><h1>Productos.</h1></div></div><Link className="text-link" href="/admin">Volver al panel</Link></header><nav className="admin-nav" aria-label="Secciones del panel"><Link href="/admin">Pedidos</Link><Link href="/admin/envios">Envíos</Link><Link className="active" href="/admin/productos">Productos</Link><Link href="/admin/categorias">Categorías</Link></nav><div className="catalog-layout"><section className="settings-section"><span className="eyebrow">Alta rápida</span><h2>Nuevo producto.</h2><p className="settings-help">Se crea como borrador. Luego podrás agregar variantes, imágenes, atributos y publicar.</p><form className="catalog-form" onSubmit={createProduct}><label>Nombre<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ej. Zapatilla Patio" required /></label><label>Precio<input value={price} onChange={(event) => setPrice(event.target.value)} inputMode="decimal" placeholder="$ 0" required /></label><label>Categoría principal<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)} required><option value="">Elegir categoría</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><button className="button-dark" type="submit">Crear borrador</button>{message && <span className="saved-message" role="status">{message}</span>}{error && <span className="auth-error" role="alert">{error}</span>}</form></section><section className="settings-section"><div className="panel-title-row"><div><span className="eyebrow">Inventario</span><h2>{products.length} productos.</h2></div><Link className="text-link" href="/admin/categorias">Gestionar categorías</Link></div><div className="product-admin-list">{products.map((product) => <div className="product-admin-row" key={product.id}><div><strong>{product.name}</strong><small>/{product.slug} · {product.brand || "Sin marca"}</small></div><span>{new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(product.price)}</span><span className={`status status-${product.status}`}>{product.status === "draft" ? "Borrador" : "Publicado"}</span></div>)}</div></section></div></main>;
}
