"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

export default function ShippingSettingsPage() {
  const [saved, setSaved] = useState(false);
  return <main className="admin"><header className="admin-head"><div className="admin-brand"><Link className="brand" href="/"><Image src="/LOGO.jpeg" alt="" width={35} height={35} /> chifle.</Link><div><span className="eyebrow">Panel de control</span><h1>Configurá envíos.</h1></div></div><Link className="text-link" href="/admin">Volver a pedidos</Link></header><nav className="admin-nav" aria-label="Secciones del panel"><Link href="/admin">Pedidos</Link><Link className="active" href="/admin/envios">Envíos</Link><button type="button">Productos</button><button type="button">Configuración</button></nav><form className="settings-grid" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><section className="settings-section"><div className="panel-title-row"><div><span className="eyebrow">Envío nacional</span><h2>Andreani</h2></div><label className="switch-line"><input type="checkbox" defaultChecked /> Activo</label></div><p className="settings-help">Cotización real según destino y paquete cuando las credenciales de Andreani estén conectadas.</p><div className="form-row"><label>Código postal de origen<input defaultValue="5012" inputMode="numeric" /></label><label>Tiempo estimado<input defaultValue="3 a 7 días hábiles" /></label></div></section><section className="settings-section"><div className="panel-title-row"><div><span className="eyebrow">Entrega urbana</span><h2>Cadetería</h2></div><label className="switch-line"><input type="checkbox" defaultChecked /> Activo</label></div><p className="settings-help">Disponible únicamente dentro del anillo de Circunvalación de Córdoba.</p><div className="form-row"><label>Tarifa fija<input defaultValue="$ 4.500" /></label><label>Zona cubierta<input defaultValue="Dentro de Circunvalación" /></label></div></section><section className="settings-section"><div className="panel-title-row"><div><span className="eyebrow">Sin costo de envío</span><h2>Retiro local</h2></div><label className="switch-line"><input type="checkbox" defaultChecked /> Activo</label></div><p className="settings-help">La dirección completa se muestra luego de confirmar la compra.</p><div className="form-row"><label>Zona de retiro<input defaultValue="Córdoba Capital" /></label><label>Disponibilidad<input defaultValue="Lun a Vie · 10 a 18 h" /></label></div></section><section className="settings-section"><div className="panel-title-row"><div><span className="eyebrow">Regla opcional</span><h2>Envío gratis</h2></div><label className="switch-line"><input type="checkbox" /> Activo</label></div><p className="settings-help">Dejá desactivado hasta definir el margen de la tienda.</p><label>Monto mínimo<input defaultValue="$ 150.000" /></label></section><div className="settings-actions"><button className="button-dark" type="submit">Guardar configuración</button>{saved && <span className="saved-message" role="status">Configuración guardada.</span>}</div></form></main>;
}
